### ISSUE TITLE
Repeatedly processing same message

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/hubot-rocketchat#76] opened 2015-11-20 14:51 UTC
Under certain high load scenario, hubot may repeatedly process the same message (internally, observable only on logs).

We need community help to reproduce this - please comment below if you have observed this or can help.

So far, it has only been observed on configurations with:
- hubot working across 30+ active rooms with constant message streams

**Comment by geekgonecrazy** [comment] 2016-08-23 17:04
I think #121 might be a duplicate of this?  Does this still happen?

**Comment by timkinnane** [comment] 2018-04-19 04:52
I think this has been resolved with updated streamer in Rocket.Chat.

**Closed by timkinnane** 2018-04-19 04:52 UTC
Labels: bug, help wanted
