### ISSUE TITLE
Room id not resolved

### ISSUE THREAD

**Issue by eliecharra** [RocketChat/hubot-rocketchat#98] opened 2016-02-16 15:55 UTC
Hi,

When using third party scripts like https://www.npmjs.com/package/hubot-gitlab-hooks, the room name is no resolved as roomId when [sending message through web hooks](https://github.com/spruce/hubot-gitlab-hooks/blob/master/src/gitlab.coffee#L71).

`http://hubot.mydomain.com/gitlab/web?targets=my-room`

`INFO Sending Message To Room: my-room`

To make gitlab hook working, we need to setup the web hook giving room internal id 

`http://hubot.mydomain.com/gitlab/web?targets=GE4K9jFM2grNt5W2P`

Solved it on my fork with this (ugly?) fix https://github.com/kitpages/hubot-rocketchat/commit/3c4634123a340b3264b5d6d9231e86a32d9ec142

**Comment by eliecharra** [comment] 2016-02-17 11:04
Same issue with sentry script, https://github.com/bolasblack/hubot-sentry/blob/master/src/sentry.coffee#L21

**Comment by chkal** [comment] 2016-02-19 13:50
And with this one:

https://github.com/halkeye/hubot-jenkins-notifier/

I think this should be supported by the rocketchat driver...

**Comment by geekgonecrazy** [comment] 2016-02-19 16:09
So the issue is that we are not converting room name to roomid on the sendMessage function.

We have a function that will do this:
https://github.com/RocketChat/hubot-rocketchat/blob/master/src/rocketchat_driver.coffee#L24

The problem I foresee here is if we put this in the sendMessage function we are introducing a bit of delay while it goes finds the id, then it sends.

The solution might be to maintain a map in the driver.  So that this delay only happens once.

We welcome any PR's to solve this.

**Comment by Sing-Li** [comment] 2016-02-19 17:42
Yes, an LRU cache of about 10 slots will be perfect.   PRs welcomed!

**Comment by chkal** [comment] 2016-02-20 08:27
Hey! I would love to implement this. Just a few questions:

* Should the caching go into RocketChatBotAdapter or RocketChatDriver? From your comments it looks like you prefer the driver?
* Wouldn't it make sense to add the caching directly to `getRoomId` in the driver? This way all other methods calling `getRoomId` would benefit from the caching.
* Any preference about which npm cache module I should use?

**Comment by chkal** [comment] 2016-02-20 16:52
I just hacked a bit on this. This is the first version of the patch that fixes this issue: 499c398b124970baa931972732c97ad9a96737bf

What do you think? The maximum age of cached room ids is currently set to 20 seconds, but we could make this configurable.

Please note that I'm not very familiar with CoffeeScript. So I'm not sure if the code is so clean as it should be. :)

Any feedback welcome!

**Comment by geekgonecrazy** [comment] 2016-02-20 17:14
@chkal awesome!  

That was quick!  Looks great, please open a PR so we can finish reviewing and get this great addition merged :smile:

**Comment by chkal** [comment] 2016-02-20 17:19
@geekgonecrazy See: #99

**Closed** 2016-02-21 19:43 UTC

**Comment by eliecharra** [comment] 2016-03-04 14:02
Good job :+1:
